version: '3.1'

services:

  db_service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hello1234
      MYSQL_DATABASE: helloworld
    ports:
      - 3306:3306
  
  phpmyadmin_service:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - db_service:db
    environment:
      PMA_HOST: db_service